# Change these first
owner: kiondaga # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Kiondaga Lodge
    url: https:/kiondaga.org
  - name: Trading Post
    url: https://tradingpost.kiondaga.org
  - name: Dev
    url: https://dev.kiondaga.org
  - name: Stats
    url: https://stats.kiondaga.org
  - name: Portal
    url: https://portal.kiondaga.org
  - name: Social
    url: https://social.kiondaga.org
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kiondaga.org
  # baseUrl: /your-repo-name
  logoUrl: https://kiondaga.org/wp-content/uploads/2021/05/OA_Trademark_FullColor.png
  name: Status - Kiondaga Lodge
  introTitle: "Kiondaga Lodge - Web Status"
  introMessage: Welcome!
  navbar:
    - title: Kiondaga Lodge Website
      href: https:/kiondaga.org
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kiondaga/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
