owner: kiondaga # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website - Production
    url: https://kiondaga.org
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  - name: Website - Development
    url: https://dev.kiondaga.org/.well-known/ping.html
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  - name: Trading Post - Production
    url: https://prod-tradingpost.kiondaga.org/.well-known/ping.html
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  - name: Trading Post - Development
    url: https://dev-tradingpost.kiondaga.org/.well-known/ping.html
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  - name: Statistics
    url: https://stats.kiondaga.org
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  - name: Committee Portal
    url: https://portal.kiondaga.org
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  - name: Social Links
    url: https://social.kiondaga.org
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  - name: Static Content
    url: https://static.kiondaga.org/ping/
    icon: https://content.kiondaga.org/favicon.ico
  - name: Static Content 2
    url: https://content.kiondaga.org/ping/
    icon: https://content.kiondaga.org/favicon.ico
  - name: URL Shortener
    url: https://kionda.ga/ping/
    icon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
    
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1,13 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 6,18 * * *"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kiondaga.org
  # baseUrl: /your-repo-name
  logoUrl: https://content.kiondaga.org/brand/Trademark/OA_Trademark_FullColor.png
  favicon: https://content.kiondaga.org/brand/Trademark/cropped-OA_Trademark-10-180x180.png
  name: Status - Kiondaga Lodge
  introTitle: "Kiondaga Lodge - Website Status"
  introMessage: Welcome to the status page for Kiondaga Lodge. This site tracks uptime and issues for Kiondaga Lodge websites. Kiondaga Lodge has proudly served Buffalo Trace Council and the Order of the Arrow since 1949. Read more about the lodge on [our website](https://kiondaga.org/about/).
  navbar:
    - title: Kiondaga Lodge Website
      href: https://kiondaga.org
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kiondaga/status
  themeUrl: https://content.kiondaga.org/css/oastatus.css
  robotsText: "User-agent: * \n Disallow: /"
  css: body{font-family:museo-sans,sans-serif} h1{font-family:museo-slab,sans-serif} nav{color:#E6E7E8}
  links:
    - rel: stylesheet
      href: https://use.typekit.net/uvm0mix.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - lukebsa

commitMessages:
  commitAuthorName: "Kiondaga Lodge Bot"
  commitAuthorEmail: "git@kiondaga.org"

i18n:
  footer: Website Status | [Kiondaga Lodge](https://kiondaga.org) - Buffalo Trace Council | [Site Info & Policies](https://kiondaga.org/site-information-policies/)
