owner: kiondaga # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website - Production
    url: https://kiondaga.org
  - name: Website - Development
    url: https://dev.kiondaga.org
  - name: Website - Staging
    url: https://stage.kiondaga.org
  - name: Trading Post - Production
    url: https://tradingpost.kiondaga.org
  - name: Trading Post - Development
    url: https://dev.tradingpost.kiondaga.org
  - name: Statistics
    url: https://stats.kiondaga.org
  - name: Committee Portal
    url: https://portal.kiondaga.org
  - name: Social Links
    url: https://social.kiondaga.org
  - name: URL Shortener
    url: $KIO_LINK
    icon: https://kiondaga.org/wp-content/uploads/2021/05/cropped-OA_Trademark-10-180x180.png
    
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kiondaga.org
  # baseUrl: /your-repo-name
  logoUrl: https://kiondaga.org/wp-content/uploads/2021/05/OA_Trademark_FullColor.png
  favicon: https://kiondaga.org/wp-content/uploads/2021/05/cropped-OA_Trademark-10-180x180.png
  name: Status - Kiondaga Lodge
  introTitle: "Kiondaga Lodge - Website Status"
  introMessage: Welcome to the status page for Kiondaga Lodge. This site tracks uptime and issues for Kiondaga Lodge websites. Kiondaga Lodge has proudly served Buffalo Trace Council and the Order of the Arrow since 1949. Read more about the lodge on [our website](https://kiondaga.org/about/).
  navbar:
    - title: Kiondaga Lodge Website
      href: https://kiondaga.org
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/kiondaga/status
  themeUrl: https://kiondaga.org/oastatus.css
  robotsText: "User-agent: * \n Disallow: /"
  css: body{font-family:'Museo Sans',sans-serif} h1{font-family:'Museo Slab',sans-serif} nav{color:#E6E7E8}
  links:
    - rel: stylesheet
      href: https://use.typekit.net/uvm0mix.css

i18n:
  footer: [Kiondaga Lodge](https://kiondaga.org), Buffalo Trace Council | [Site Info & Policies](https://kiondaga.org/site-information-policies/)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - lukebsa
